#!/usr/bin/env node
/**
 * import-tokens.mjs — CLI entry for the figma-tokens skill.
 *
 * The JSON→CSS direction of the token pipeline. Reads the committed Figma export
 * under tokens/figma-export/, classifies EVERY leaf token, and emits:
 *   - generated CSS blocks injected into src/css/globals.css
 *     between `figma:<block>` START/END markers (hand-authored tokens OUTSIDE the
 *     markers are never touched);
 *   - src/css/mode-custom-experimental.css (quarantine);
 *   - tokens/audits/token-coverage-report.md (every source token → destination or
 *     skipped:<reason>) and tokens/audits/generated-blocks.css (preview).
 *
 * Coverage gate: refuses to apply (exit 1) if any leaf is unclassified or a
 * generated name collides with a hand-authored declaration outside the markers.
 *
 * Usage:
 *   node .claude/skills/figma-tokens/scripts/import-tokens.mjs           # report-only
 *   node .claude/skills/figma-tokens/scripts/import-tokens.mjs --apply   # inject + quarantine
 *   ... [--src DIR] [--globals FILE] [--quarantine FILE] [--coverage FILE] [--blocks FILE]
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DEFAULT_CONFIG, defaultPaths, findRepoRoot, loadExport } from './lib/loader.mjs';
import { classify } from './lib/classifier.mjs';
import {
  assertNoCollisions,
  extractGeneratedNames,
  findCollisions,
  injectAll,
} from './lib/injector.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));

// ── Args ─────────────────────────────────────────────────────────────────────
const argv = process.argv.slice(2);
const APPLY = argv.includes('--apply');
const flag = (name) => {
  const eq = argv.find((a) => a.startsWith(`--${name}=`));
  if (eq) return eq.slice(name.length + 3);
  const i = argv.indexOf(`--${name}`);
  return i !== -1 && argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[i + 1] : null;
};

// ── Paths ────────────────────────────────────────────────────────────────────
const repoRoot = findRepoRoot(HERE) || resolve(HERE, '../../../..');
const dft = defaultPaths(repoRoot);
const paths = {
  srcDir: flag('src') ? resolve(flag('src')) : dft.srcDir,
  globals: flag('globals') ? resolve(flag('globals')) : dft.globals,
  quarantine: flag('quarantine') ? resolve(flag('quarantine')) : dft.quarantine,
  coverage: flag('coverage') ? resolve(flag('coverage')) : dft.coverage,
  blocksPreview: flag('blocks') ? resolve(flag('blocks')) : dft.blocksPreview,
};
const rel = (p) => relative(repoRoot, p).replace(/\\/g, '/');

// ── Pipeline: load → classify ────────────────────────────────────────────────
const files = loadExport(paths.srcDir, { repoRoot, config: DEFAULT_CONFIG });
const result = classify(files);
const { blocks, quarantineCss, warnings, unclassified, totalLeaves, totalClassified, counts } = result;

// ── Coverage report (always written, even on failure, so it can be inspected) ──
const reportLines = [];
reportLines.push(`# Token coverage report`);
reportLines.push('');
reportLines.push(`Source: \`${rel(paths.srcDir)}/\` · Generated by the \`figma-tokens\` skill`);
reportLines.push('');
reportLines.push(
  `**${totalClassified}/${totalLeaves} leaf tokens classified.** ${unclassified.length === 0 ? '✅ none lost' : '❌ ' + unclassified.length + ' UNCLASSIFIED'}`,
);
reportLines.push('');
for (const f of files) {
  reportLines.push(`## ${f.collection} — \`${f.file}\` (${f.leaves.length})`);
  reportLines.push('');
  reportLines.push('| Figma token | → destination |');
  reportLines.push('|---|---|');
  for (const e of f.entries.sort((a, b) => a.key.localeCompare(b.key))) reportLines.push(`| \`${e.key}\` | ${e.dest} |`);
  reportLines.push('');
}
if (warnings.length) {
  reportLines.push(`## ⚠ warnings`);
  reportLines.push('');
  warnings.forEach((w) => reportLines.push(`- ${w}`));
  reportLines.push('');
}
if (unclassified.length) {
  reportLines.push(`## ❌ unclassified`);
  reportLines.push('');
  unclassified.forEach((u) => reportLines.push(`- ${u}`));
  reportLines.push('');
}
mkdirSync(dirname(paths.coverage), { recursive: true });
writeFileSync(paths.coverage, reportLines.join('\n'), 'utf8');

// ── Blocks preview ─────────────────────────────────────────────────────────────
const previewLines = [`/* PREVIEW of generated blocks — do not import. Apply via --apply. */`];
for (const [k, v] of Object.entries(blocks)) previewLines.push(`\n/* ===== ${k} ===== */\n${v}`);
previewLines.push(`\n/* ===== quarantine file ===== */\n${quarantineCss}`);
mkdirSync(dirname(paths.blocksPreview), { recursive: true });
writeFileSync(paths.blocksPreview, previewLines.join('\n'), 'utf8');

// ── Coverage gate (blocks --apply) ─────────────────────────────────────────────
if (unclassified.length) {
  console.error(`[import] ❌ ${unclassified.length} UNCLASSIFIED leaves — see report; refusing to apply`);
  console.error(`[import] coverage → ${rel(paths.coverage)}`);
  process.exit(1);
}

// ── Apply: collision check → inject markers → write globals + quarantine ───────
if (APPLY) {
  let css = readFileSync(paths.globals, 'utf8');
  const collisions = findCollisions(css, extractGeneratedNames(blocks));
  try {
    assertNoCollisions(collisions);
  } catch (err) {
    console.error(`[import] ❌ ${err.message.replace(/^name collisions[^:]*: /, 'name collisions:\n  ').replace(/, /g, '\n  ')}`);
    process.exit(1);
  }
  css = injectAll(css, blocks);
  writeFileSync(paths.globals, css, 'utf8');
  writeFileSync(paths.quarantine, quarantineCss, 'utf8');
  console.log(`[import] applied ${Object.keys(blocks).length} blocks → ${rel(paths.globals)}; wrote quarantine.`);
}

// ── Summary ────────────────────────────────────────────────────────────────────
console.log(
  `[import] ${totalClassified}/${totalLeaves} classified; primitives=${counts.primitives} semantics=${counts.semantics} alpha=${counts.alpha} shadow/blur=${counts.shadowBlur} custom=${counts.custom}`,
);
console.log(`[import] coverage → ${rel(paths.coverage)}`);
if (warnings.length) console.log(`[import] ⚠ ${warnings.length} warnings (see report)`);
