/**
 * report.mjs — render the code → Figma divergence report (pure, deterministic).
 *
 * `code-to-figma` pushes the NON-semantic tokens; everything it does NOT push is
 * recorded here so the divergence stays visible. That's two populations:
 *   - the excluded semantics (`--primary`, `--background`, … = Mode/base), and
 *   - the alias-guarded variables (a Figma var that is an ALIAS is never flattened).
 *
 * Code is canonical: an un-pushed token that DIVERGES stays out of sync until you
 * change the underlying primitive (cascade via alias) or push it by hand
 * (`reverse` → Tokens Studio). This module only formats — the caller does the I/O
 * (writes `tokens/audits/code-to-figma-report.md`) and stamps any timestamp.
 *
 * Entry shape (every field is missing-safe → renders as "—"):
 *   {
 *     token,                                   // e.g. "--primary"
 *     code:  { file, selector, value },        // e.g. globals.css · :root · #0060C8
 *     figma: { collection, mode, path, value } // e.g. Mode · Light · base/primary · #0F9173
 *   }
 *
 * Groups:
 *   diverging  ⚠️  un-pushed AND code ≠ Figma (a hand-edit that won't reach Figma)
 *   aligned    ✓   un-pushed but already equal on both sides (no action)
 *   aliasSkip  🔒  Figma variable is an alias — never flattened to a literal
 */

const DASH = '—';
/** Escape a markdown table cell (only the pipe can break a row). */
const esc = (s) => String(s ?? DASH).replace(/\|/g, '\\|');
/** Monospace one segment, falling back to the em-dash placeholder. */
const mono = (s) => (s === undefined || s === null || s === '' ? DASH : `\`${esc(s)}\``);

const codeCell = (c = {}) => [c.file, c.selector, c.value].map(mono).join(' · ');
const figmaCell = (f = {}) => [f.collection, f.mode, f.path, f.value].map(mono).join(' · ');

/** One markdown table for a group, or an italic "_none_" when empty. */
function table(entries) {
  if (!entries.length) return '_none_\n';
  const head =
    '| Token | Code (file · selector · value) | Figma (collection · mode · path · value) |\n' +
    '|---|---|---|\n';
  const rows = entries
    .map((e) => `| ${mono(e.token)} | ${codeCell(e.code)} | ${figmaCell(e.figma)} |`)
    .join('\n');
  return head + rows + '\n';
}

/**
 * Build the full report markdown.
 * @param {{diverging?: object[], aligned?: object[], aliasSkip?: object[]}} groups
 * @param {{fileKey?: string, mode?: string, generated?: string}} [meta]
 *        `generated` is an optional caller-supplied stamp (kept out of here so the
 *        function stays pure/testable). `mode` = the transport the diff used (MCP).
 * @returns {string} markdown for tokens/audits/code-to-figma-report.md
 */
export function renderDivergenceReport(groups = {}, meta = {}) {
  const diverging = groups.diverging ?? [];
  const aligned = groups.aligned ?? [];
  const aliasSkip = groups.aliasSkip ?? [];

  const lines = [];
  lines.push('# code → Figma — divergence report');
  lines.push('');
  lines.push(
    '> Generated by the `figma-tokens` skill (`code-to-figma`). Lists every token **not** ' +
      'pushed to Figma — the excluded semantics + the alias-skips. Code is canonical; a ' +
      'diverging row stays out of sync until you change the underlying primitive (cascade ' +
      'via alias) or push it by hand (`reverse` → Tokens Studio).',
  );
  lines.push('');
  if (meta.fileKey) lines.push(`- Figma file: \`${esc(meta.fileKey)}\``);
  if (meta.mode) lines.push(`- Transport: ${esc(meta.mode)}`);
  if (meta.generated) lines.push(`- Generated: ${esc(meta.generated)}`);
  lines.push(
    `- Summary: ⚠️ ${diverging.length} diverging · ✓ ${aligned.length} aligned · 🔒 ${aliasSkip.length} alias-skip`,
  );
  lines.push('');
  lines.push('## ⚠️ Diverging — code ≠ Figma (un-pushed; hand-edits that won’t reach Figma)');
  lines.push('');
  lines.push(table(diverging));
  lines.push('## ✓ Aligned — un-pushed but equal on both sides (no action)');
  lines.push('');
  lines.push(table(aligned));
  lines.push('## 🔒 Alias-skip — Figma variable is an alias (never flattened to a literal)');
  lines.push('');
  lines.push(table(aliasSkip));

  return lines.join('\n').replace(/\n+$/, '\n');
}
